# https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    ports:
      - 9200:9200
    user: "1000:1000" # Run as opensearch user
    volumes:
      # mount the data directory to persist the data
      - ${OPENSEARCH_DATA_DIR:-$HOME/scratch/longeval/opensearch/data}:/usr/share/opensearch/data
      - ${OPENSEARCH_SNAPSHOT_DIR:-$HOME/scratch/longeval/opensearch/snapshots}:/mnt/snapshots
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD?not set}
      - path.repo=/mnt/snapshots
      - plugins.security.disabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.allocator.existing_shards_allocator.batch_enabled=true
      - knn.memory.circuit_breaker.enabled=true
      - knn.memory.circuit_breaker.limit=256mb
      # no replicas for single-node setup
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx16g
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=60s" ]
      interval: 15s
      timeout: 60s
      retries: 5
    ulimits:
      # Set memlock to unlimited (no soft or hard limit)
      memlock:
        soft: -1
        hard: -1
      # Maximum number of open files for the opensearch user - set to at least 65536
      nofile:
        soft: 65536
        hard: 65536
  # add the opensearch ui too
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    ports:
      - 5601:5601
    environment:
      # https://stackoverflow.com/questions/74178194/how-can-i-remove-the-login-page-when-running-opensearch-dashboards-in-docker
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    depends_on:
      opensearch:
        condition: service_healthy
