# https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
services:
  opensearch:
    image: opensearchproject/opensearch:2
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      # mount the data directory to persist the data
      - ./data/longeval/opensearch-v1:/usr/share/opensearch/data
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD==${OPENSEARCH_PASSWORD?not set}
      - plugins.security.disabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      # no replicas for single-node setup
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx8g
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
