data:
  input_rootfolder: "/storage/scratch1/8/amiyaguchi3/longeval/2025/bm25/retrieval_joined"
  output_folder: "/storage/scratch1/8/amiyaguchi3/longeval/2025/bm25/reranked"

parallel:
  max_concurrency: 16

reranking:
  gpu: True
  model_name: "cross-encoder"
  model_type: "cross-encoder"
  lang: "fr"
  batch_size: 50
